version: '3'
services:
  server:
     image: node:8.9.4
     #  restart: always
     ports:
       - "9000:9000"
     volumes:
       - ./server:/www/server/
     working_dir: /www/server/
     command: bash -c "npm install && npm run dev"
     depends_on:
       - mysql
     links:
       - mysql
     environment:
       - MYSQL_HOST=mysql
       - MYSQL_DATABASE=blog
       - MYSQL_USER=developer
       - MYSQL_PASSWORD=developer
       - HOME_PORT=9000
  admin:
     image: node:8.9.4
     ports:
       - "8080:8080"
     volumes:
       - ./admin:/www/admin/
     working_dir: /www/admin/
     command: bash -c "npm install && npm run start"
     depends_on:
       - server
  client:
     image: node:8.9.4
     ports:
       - "3000:3000"
     volumes:
       - ./client:/www/client/
     working_dir: /www/client/
     command: bash -c "npm install && npm run dev"
     depends_on:
       - server
  mysql:
    image: mysql:5.7
    # restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
