version: '3'
services:
  server:
     image: node:8.9.4
     #  restart: always
     ports:
       - "3000:3000"
       - "0.0.0.0:9222:9222"
     volumes:
       - ./server/:/www/server/
       - ./server/logs:/root/.npm/_logs/
     working_dir: /www/server/
     command: bash -c "npm install nodemon -g && npm install --no-bin-links && npm run start"
     depends_on:
       - mysql
     links:
       - mysql
     environment:
       - MYSQL_HOST=mysql
       - MYSQL_DATABASE=blog
       - MYSQL_USER=developer
       - MYSQL_PASSWORD=developer
       - NODE_ENV=development
       - HOST=0.0.0.0
       - HOME_PORT=3000
  admin:
     image: node:8.9.4
     ports:
       - "8080:8080"
     volumes:
       - ./admin/:/www/admin/
       - ./admin/logs:/root/.npm/_logs/
     working_dir: /www/admin/
     command: bash -c "npm install webpack-dev-server -g && npm install --no-bin-links && npm run start"
     environment:
       - NODE_ENV=development
       - HOST=0.0.0.0
       - PORT=8080
     depends_on:
       - server
  client:
     image: node:8.9.4
     ports:
       - "9000:9000"
     volumes:
       - ./client/:/www/client/
       - ./client/logs:/root/.npm/_logs/
     working_dir: /www/client/
     command: bash -c "npm install nuxt -g && npm install --no-bin-links && npm dev"
     environment:
       - NODE_ENV=development
       - HOST=0.0.0.0
       - PORT=9000
     depends_on:
       - server
  mysql:
    image: mysql:5.7
    # restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
